// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Waypoint.BusinessIdeas.Infrastructure;

#nullable disable

namespace Waypoint.BusinessIdeas.Infrastructure.Migrations
{
    [DbContext(typeof(BusinessIdeasDbContext))]
    [Migration("20260809003238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Waypoint.BusinessIdeas.Domain.BusinessIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BusinessModel")
                        .HasColumnType("text")
                        .HasColumnName("business_model");

                    b.Property<string>("Competitors")
                        .HasColumnType("text")
                        .HasColumnName("competitors");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Customer")
                        .HasColumnType("text")
                        .HasColumnName("customer");

                    b.Property<Guid>("DreamId")
                        .HasColumnType("uuid")
                        .HasColumnName("dream_id");

                    b.Property<string>("FinancialAssumptions")
                        .HasColumnType("text")
                        .HasColumnName("financial_assumptions");

                    b.Property<string>("Market")
                        .HasColumnType("text")
                        .HasColumnName("market");

                    b.Property<string>("Marketing")
                        .HasColumnType("text")
                        .HasColumnName("marketing");

                    b.Property<string>("Operations")
                        .HasColumnType("text")
                        .HasColumnName("operations");

                    b.Property<string>("Pricing")
                        .HasColumnType("text")
                        .HasColumnName("pricing");

                    b.Property<string>("Problem")
                        .HasColumnType("text")
                        .HasColumnName("problem");

                    b.Property<string>("Risks")
                        .HasColumnType("text")
                        .HasColumnName("risks");

                    b.Property<string>("Sales")
                        .HasColumnType("text")
                        .HasColumnName("sales");

                    b.Property<string>("Solution")
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("ValueProposition")
                        .HasColumnType("text")
                        .HasColumnName("value_proposition");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_business_ideas");

                    b.HasIndex("DreamId")
                        .IsUnique()
                        .HasDatabaseName("ix_business_ideas_dream_id");

                    b.ToTable("business_ideas", (string)null);
                });

            modelBuilder.Entity("Waypoint.BusinessIdeas.Domain.BusinessValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BusinessIdeaId")
                        .HasColumnType("uuid")
                        .HasColumnName("business_idea_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("GeneratedByAi")
                        .HasColumnType("boolean")
                        .HasColumnName("generated_by_ai");

                    b.Property<string>("RecommendedExperiments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_experiments");

                    b.Property<string>("StrongAssumptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("strong_assumptions");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unknowns")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("unknowns");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int?>("ViabilityEstimate")
                        .HasColumnType("integer")
                        .HasColumnName("viability_estimate");

                    b.Property<string>("WeakAssumptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weak_assumptions");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_business_validations");

                    b.HasIndex("BusinessIdeaId")
                        .HasDatabaseName("ix_business_validations_business_idea_id");

                    b.ToTable("business_validations", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_validations_viability_estimate_range", "viability_estimate BETWEEN 0 AND 100");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
